export const NOTES_FETCH_REQUEST='NOTES_FETCH_REQUEST'
export const NOTES_FETCH_SUCCESS='NOTES_FETCH_SUCCESS'
export const NOTES_FETCH_FAIL='NOTES_FETCH_FAIL'


export const NOTES_ADD_REQUEST='NOTES_ADD_REQUEST'
export const NOTES_ADD_SUCCESS='NOTES_ADD_SUCCESS'
export const NOTES_ADD_FAIL='NOTES_ADD_FAIL'

export const NOTES_DELETE_REQUEST='NOTES_DELETE_REQUEST'
export const NOTES_DELETE_SUCCESS='NOTES_DELETE_SUCCESS'


export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'